




global fillBackground:proc
global wait_VBLANK:proc
global drawSprite:proc
global drawRectangle:proc
global clearPreviousPosition:proc
global drawFlippedSprite:proc
global draw_game_values:proc
global draw_level_and_lives_string:proc
global display_start_screen:proc
global dispay_end_screen:proc
global printUnsignedInteger:proc
global displaystring:proc
global change_color_palette:proc
global display_congrats:proc